included:
  - Illumination
  - IlluminationTests
  - IlluminationUITests

excluded:
  - build
  - Illumination.xcodeproj

only_rules:
  - force_cast
  - force_try
  - force_unwrapping
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity

force_cast: error
force_try: error

file_length:
  warning: 700
  error: 900

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 600
  error: 900

cyclomatic_complexity:
  warning: 20
  error: 30
